# Generated by Django 5.2.5 on 2025-08-28 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_speakerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme_name', models.CharField(max_length=100)),
                ('Programme_Time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='speakers',
            name='Schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='speakers.programme'),
            preserve_default=False,
        ),
    ]
