# Generated by Django 5.2.5 on 2025-08-28 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_programme_speakers_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='Programme_Time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
