# Generated by Django 5.2.5 on 2025-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_alter_programme_programme_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakers',
            name='Schedule',
        ),
        migrations.AddField(
            model_name='speakers',
            name='Speakin_Day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='Speaking_time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
