# Generated by Django 5.2.4 on 2025-09-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_remove_speakers_schedule_speakers_speakin_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='Speaking_topic',
            field=models.CharField(blank=True, default='To be announced', max_length=200),
        ),
    ]
