# Generated by Django 5.2.4 on 2025-09-26 12:50

import youthrise.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_speakers_speaking_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerimage',
            name='image',
            field=models.ImageField(storage=youthrise.storages_backends.MediaRootS3BotoStorage(), upload_to='speaker_images/'),
        ),
    ]
