# Generated by Django 5.2.4 on 2025-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0007_alter_speakerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerimage',
            name='image',
            field=models.ImageField(upload_to='speaker_images/'),
        ),
    ]
