# Generated by Django 5.2.4 on 2025-09-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForAttending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.BigIntegerField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('NGO', 'Non-profit/NGO'), ('Government', 'Government'), ('Private Sector', 'Private Sector/Corporate'), ('Education/Academia', 'Education/Academia'), ('Healthcare', 'Healthcare'), ('Media/Comm', 'Media/Communication'), ('Student', 'Student'), ('Others', 'Others')], max_length=50)),
                ('specify_sector', models.CharField(blank=True, max_length=100)),
                ('leadership_position', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Others', 'Others')], max_length=10)),
                ('specify_other', models.CharField(blank=True, max_length=100)),
                ('participation_source', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Email Invitation', 'Email Invitation'), ('Colleague', 'Colleague'), ('Website', 'Website'), ('Partner Organization', 'Partner Organization'), ('Others', 'Others')], max_length=50)),
                ('specify_source', models.CharField(blank=True, max_length=100)),
                ('specify_reason', models.CharField(blank=True, max_length=100)),
                ('participation_type', models.CharField(blank=True, choices=[('ip', 'In-person'), ('virtual', 'Virtual/Online'), ('hybrid', 'Hybrid (some sessions in-person, some virtual)')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKAW', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS-RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory (Abuja)'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOLA', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20)),
                ('volunteer_option', models.CharField(blank=True, choices=[('Ushering', 'Ushering'), ('Media coverage', 'Media coverage'), ('Rapporteur', 'Rapporteur'), ('Security', 'Security'), ('Audio and Visual Tech', 'Audio and Visual Tech'), ('Other', 'Other')], max_length=30, null=True)),
                ('specify_volunteer', models.CharField(blank=True, max_length=100)),
                ('specify_accessiblity', models.CharField(blank=True, max_length=50)),
                ('age_range', models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-45', '36–45'), ('46-55', '46–55+')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('covered_in_the_conference', models.CharField(blank=True, max_length=200)),
                ('additional_comments', models.CharField(blank=True, max_length=100)),
                ('photography_consent', models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I Disagree')], max_length=10)),
                ('email_communication', models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I disagree')], max_length=10)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('accessibility_accommodations', models.ManyToManyField(blank=True, to='registration_app.accessibilityoption')),
                ('reason_for_attending', models.ManyToManyField(blank=True, to='registration_app.reasonforattending')),
                ('registration_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.registrationcategory')),
            ],
        ),
    ]
