# Generated by Django 5.2.4 on 2025-07-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Address',
            new_name='address',
        ),
    ]
