# Generated by Django 5.2.5 on 2025-08-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_rename_address_registration_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='Registration_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration_app.registrationcategory'),
            preserve_default=False,
        ),
    ]
