# Generated by Django 5.2.5 on 2025-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_registrationcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Registration_category',
            new_name='registration_category',
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
