# Generated by Django 5.2.5 on 2025-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_rename_registration_category_registration_registration_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
