# Generated by Django 5.2.5 on 2025-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_alter_registration_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
