# Generated by Django 5.2.4 on 2025-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_registrationcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason_for_Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='Job_title',
            field=models.CharField(default='Designer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Leadership_position',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Enigineer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Organization',
            field=models.CharField(default='NGO', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Sector',
            field=models.CharField(choices=[('NGO', 'Non-profit/NGO'), ('Gov', 'Goverment'), ('PS', 'Private Sector/Corporate'), ('Edu', 'Education/Academia'), ('Health', 'Healthcare'), ('Media/Comm', 'Media/Communication'), ('Student', 'Student')], default='gov', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Specify_leader',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='participation_type',
            field=models.CharField(choices=[('ip', 'In-person'), ('Virtual/Online', 'virtual/Online'), ('Hybrid', 'Hybrid (some sessions in-person, some virtual)')], default='Online', max_length=20),
            preserve_default=False,
        ),
    ]
