# Generated by Django 5.2.4 on 2025-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0007_reason_for_attending_registration_job_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reason_for_Attending',
            new_name='ReasonForAttending',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Job_title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Specify_leader',
            new_name='specify_leader',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Leadership_position',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Sector',
        ),
        migrations.AddField(
            model_name='registration',
            name='participation_source',
            field=models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Email Invitation', 'Email Invitation'), ('Colleague', 'Colleague'), ('Website', 'Website'), ('Partner Organization', 'Partner Organization')], max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='reason_for_attending',
            field=models.ManyToManyField(blank=True, to='registration_app.reasonforattending'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('FC', 'Federal Capital Territory (Abuja)'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara')], default='Abuja', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='participation_type',
            field=models.CharField(choices=[('ip', 'In-person'), ('virtual', 'Virtual/Online'), ('hybrid', 'Hybrid (some sessions in-person, some virtual)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='leadership_position',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='sector',
            field=models.CharField(choices=[('NGO', 'Non-profit/NGO'), ('Gov', 'Government'), ('PS', 'Private Sector/Corporate'), ('Edu', 'Education/Academia'), ('Health', 'Healthcare'), ('Media/Comm', 'Media/Communication'), ('Student', 'Student')], default='gov', max_length=50),
            preserve_default=False,
        ),
    ]
