# Generated by Django 5.2.4 on 2025-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_rename_reason_for_attending_reasonforattending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='accessibility_accommodations',
            field=models.ManyToManyField(blank=True, help_text='Select any accessibility accommodations you require.', to='registration_app.accessibilityoption'),
        ),
    ]
