# Generated by Django 5.2.4 on 2025-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_accessibilityoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-45', '36–45'), ('46-55', '46–55')], max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='covered_in_the_conference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='email_communication',
            field=models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I disagree')], default='Yes', help_text='I agree to receive conference updates and future event notifications.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='photography_consent',
            field=models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I disagree')], default='yes', help_text='I consent to being photographed/recorded during the conference for promotional purposes.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='specify_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='specify_sector',
            field=models.CharField(default='NGO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='specify_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(blank=True),
        ),
    ]
