# Generated by Django 5.2.4 on 2025-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0010_registration_additional_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_communication',
            field=models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I disagree')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photography_consent',
            field=models.BooleanField(max_length=10),
        ),
    ]
