# Generated by Django 5.0.6 on 2025-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0011_alter_registration_email_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participation_source',
            field=models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Email Invitation', 'Email Invitation'), ('Colleague', 'Colleague'), ('Website', 'Website'), ('Partner Organization', 'Partner Organization'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photography_consent',
            field=models.CharField(choices=[('Agree', 'I agree')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sector',
            field=models.CharField(choices=[('NGO', 'Non-profit/NGO'), ('Gov', 'Government'), ('PS', 'Private Sector/Corporate'), ('Edu', 'Education/Academia'), ('Health', 'Healthcare'), ('Media/Comm', 'Media/Communication'), ('Student', 'Student'), ('Others', 'Others')], max_length=50),
        ),
    ]
