# Generated by Django 5.0.6 on 2025-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0012_alter_registration_participation_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='specify_leader',
            new_name='specify_other',
        ),
        migrations.AddField(
            model_name='registration',
            name='specify_accessiblity',
            field=models.CharField(default='CEO', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='accessibility_accommodations',
            field=models.ManyToManyField(blank=True, to='registration_app.accessibilityoption'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='leadership_position',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Others', 'Others')], max_length=10),
        ),
    ]
