# Generated by Django 5.0.6 on 2025-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0013_rename_specify_leader_registration_specify_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='createdat',
            field=models.DateField(auto_now_add=True, default="2025-08-12"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='photography_consent',
            field=models.CharField(choices=[('Agree', 'I agree'), ('Disagree', 'I Disagree')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sector',
            field=models.CharField(choices=[('NGO', 'Non-profit/NGO'), ('Government', 'Government'), ('Private Sector', 'Private Sector/Corporate'), ('Education/Academia', 'Education/Academia'), ('Healthcare', 'Healthcare'), ('Media/Comm', 'Media/Communication'), ('Student', 'Student'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='specify_accessiblity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='specify_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
