# Generated by Django 5.0.6 on 2025-09-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0014_registration_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
