# Generated by Django 5.0.6 on 2025-09-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0015_rename_createdat_registration_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created_at',
            new_name='registered_on',
        ),
    ]
