# Generated by Django 5.0.6 on 2025-09-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0016_rename_created_at_registration_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKAW', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS-RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory (Abuja)'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOLA', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20),
        ),
    ]
