# Generated by Django 5.2.4 on 2025-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0017_alter_registration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-45', '36–45'), ('46-55', '46–55+')], max_length=10),
        ),
    ]
