# Generated by Django 5.2.4 on 2025-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0018_alter_registration_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='specify_volunteer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='volunteer_option',
            field=models.CharField(blank=True, choices=[('Ushering', 'Ushering'), ('Media coverage', 'Media coverage'), ('Rapporteur', 'Rapporteur'), ('Security', 'Security'), ('Audio and Visual Tech', 'Audio and Visual Tech'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
