# Generated by Django 5.2.4 on 2025-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0019_registration_specify_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='leadership_position',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participation_type',
            field=models.CharField(blank=True, choices=[('ip', 'In-person'), ('virtual', 'Virtual/Online'), ('hybrid', 'Hybrid (some sessions in-person, some virtual)')], max_length=20),
        ),
    ]
