# Generated by Django 5.2.4 on 2025-09-25 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_viewingdayscategory_viewingdays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencedate',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='conferencedate',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
