# Generated by Django 5.2.4 on 2025-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_rename_date_conferencedate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencedate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
