# Generated by Django 5.2.4 on 2025-07-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
