# Generated by Django 5.2.5 on 2025-08-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.CharField(default='speaker', max_length=100),
            preserve_default=False,
        ),
    ]
