# Generated by Django 5.2.5 on 2025-08-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_gallery_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='position',
        ),
    ]
