# Generated by Django 5.2.4 on 2025-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='Organization',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='industry_segment',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='organization_description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='primary_contact',
            field=models.CharField(default='General', max_length=15),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='what_are_you_exhibiting',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='email',
            field=models.EmailField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='firstname',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='lastname',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='organization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
