# Generated by Django 5.2.4 on 2025-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_remove_exhibition_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='industry_segment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='organization_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='primary_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='what_are_you_exhibiting',
            field=models.CharField(max_length=50),
        ),
    ]
