# Generated by Django 5.2.4 on 2025-07-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_alter_exhibition_email_alter_exhibition_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='what_are_you_exhibiting',
            new_name='what_exhibiting',
        ),
    ]
