# Generated by Django 5.2.4 on 2025-09-10 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_rename_what_are_you_exhibiting_exhibition_what_exhibiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
