# Generated by Django 5.2.4 on 2025-09-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_exhibition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
