# Generated by Django 5.2.4 on 2025-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zoom Stream', max_length=100)),
                ('meeting_id', models.CharField(max_length=100)),
            ],
        ),
    ]
