# Generated by Django 5.2.4 on 2025-09-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='name',
        ),
        migrations.AddField(
            model_name='stream',
            name='streaming_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
