# Generated by Django 5.2.4 on 2025-09-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stream_meeting_id_remove_stream_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('content', models.CharField(choices=[('NGO', 'NGO 1'), ('Community groups', 'Community groups'), ('Faith-Based Organization', 'Faith-Based Organization'), ('Association or Union', 'Association or Union')], max_length=255)),
                ('Location', models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKAW', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS-RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory (Abuja)'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOLA', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20)),
                ('implementing', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=255)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('specify_others', models.CharField(blank=True, max_length=100)),
                ('describe_story', models.TextField()),
                ('make_difference', models.TextField()),
                ('speak_about', models.CharField(choices=[('Yes, I would like to speak', 'Yes, I would like to speak'), ('No, but I am open to my story being shared', 'No, but I am open to my story being shared')], max_length=100)),
                ('organization_website', models.URLField(blank=True)),
                ('portfolio_link', models.URLField()),
                ('social_media', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.work')),
            ],
        ),
    ]
