# Generated by Django 5.2.4 on 2025-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_work_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='specify_works',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.CharField(choices=[('NGO', 'NGO'), ('Community groups', 'Community groups'), ('Faith-Based Organization', 'Faith-Based Organization'), ('Association or Union', 'Association or Union'), ('Others', 'Others')], max_length=255),
        ),
    ]
