# Generated by Django 5.2.4 on 2025-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
