# Generated by Django 5.2.4 on 2025-09-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='mmessage',
            new_name='message',
        ),
    ]
