# Generated by Django 5.2.4 on 2025-07-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('package', models.CharField(choices=[('basic', 'Basic Package'), ('premium', 'Premium'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
    ]
