# Generated by Django 5.2.4 on 2025-09-10 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_sponsorshippackage_alter_sponsors_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
